# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

from typing import *
from collections import *
from heapq import *
from bisect import *

class Node:
    def __init__(self, val = 0, neighbors = None):
        self.val = val
        self.neighbors = neighbors if neighbors is not None else []



# ==== YOUR SOLUTION HERE ====


# Test cases for clone-graph
_test_cases = [
    [[2, 4], [1, 3], [2, 4], [1, 3]],
    [[]],
    [],
]

def _build_graph(adj):
    if not adj:
        return None, []
    nodes = [Node(i + 1) for i in range(len(adj))]
    for node, neighbors in zip(nodes, adj):
        node.neighbors = [nodes[val - 1] for val in neighbors]
    return nodes[0], nodes

def _collect(node):
    if node is None:
        return []
    seen = {}
    q = deque([node])
    while q:
        cur = q.popleft()
        if cur.val in seen:
            continue
        seen[cur.val] = cur
        q.extend(cur.neighbors)
    return [seen[k] for k in sorted(seen)]

def _dump_graph(node):
    nodes = _collect(node)
    return [sorted(neighbor.val for neighbor in node.neighbors) for node in nodes]

def check(candidate):
    passed = 0
    failed = []
    for i, adj in enumerate(_test_cases, 1):
        root, original_nodes = _build_graph(adj)
        try:
            cloned = candidate(root)
            clone_nodes = _collect(cloned)
            assert _dump_graph(cloned) == [sorted(n) for n in adj]
            assert all(node not in original_nodes for node in clone_nodes)
            passed += 1
        except AssertionError:
            failed.append((i, 'wrong answer'))
        except Exception as e:
            failed.append((i, type(e).__name__ + ': ' + str(e)))
    print(f'{passed}/{len(_test_cases)} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, err in failed:
            print(f'  Test #{i}: {err}')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution().cloneGraph)
