# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

from typing import *
from collections import *
from heapq import *
from bisect import *

class Node:
    def __init__(self, x: int, next: 'Node' = None, random: 'Node' = None):
        self.val = int(x)
        self.next = next
        self.random = random



# ==== YOUR SOLUTION HERE ====


# Test cases for copy-list-with-random-pointer
_test_cases = [
    [[7, None], [13, 0], [11, 4], [10, 2], [1, 0]],
    [[1, 1], [2, 1]],
    [],
]

def _build_random_list(items):
    nodes = [Node(v) for v, _ in items]
    for i, node in enumerate(nodes[:-1]):
        node.next = nodes[i + 1]
    for node, (_, random_index) in zip(nodes, items):
        node.random = None if random_index is None else nodes[random_index]
    return (nodes[0] if nodes else None), nodes

def _dump_random_list(head):
    nodes = []
    cur = head
    while cur:
        nodes.append(cur)
        cur = cur.next
    index = {node: i for i, node in enumerate(nodes)}
    return [[node.val, None if node.random is None else index.get(node.random)] for node in nodes]

def check(candidate):
    passed = 0
    failed = []
    for i, items in enumerate(_test_cases, 1):
        head, original_nodes = _build_random_list(items)
        try:
            cloned = candidate(head)
            clone_nodes = []
            cur = cloned
            while cur:
                clone_nodes.append(cur)
                cur = cur.next
            assert _dump_random_list(cloned) == items
            assert all(node not in original_nodes for node in clone_nodes)
            assert all(node.random is None or node.random not in original_nodes for node in clone_nodes)
            passed += 1
        except AssertionError:
            failed.append((i, 'wrong answer'))
        except Exception as e:
            failed.append((i, type(e).__name__ + ': ' + str(e)))
    print(f'{passed}/{len(_test_cases)} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, err in failed:
            print(f'  Test #{i}: {err}')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution().copyRandomList)
