# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

from typing import *
from collections import *
from heapq import *
from bisect import *



# ==== YOUR SOLUTION HERE ====


# Test cases for design-twitter
_test_cases = [(['Twitter', 'postTweet', 'getNewsFeed', 'follow', 'postTweet', 'getNewsFeed', 'unfollow', 'getNewsFeed'], [[], [1, 5], [1], [1, 2], [2, 6], [1], [1, 2], [1]], [None, None, [5], None, None, [6, 5], None, [5]])]

def check(cls):
    passed = 0
    failed = []
    for case_num, (ops, args, expected) in enumerate(_test_cases, 1):
        obj = None
        actual = []
        try:
            for op, arg in zip(ops, args):
                if obj is None:
                    obj = cls(*arg)
                    actual.append(None)
                else:
                    actual.append(getattr(obj, op)(*arg))
            assert actual == expected
            passed += 1
        except AssertionError:
            failed.append((case_num, expected, actual, 'wrong answer'))
        except Exception as e:
            failed.append((case_num, expected, actual, type(e).__name__ + ': ' + str(e)))
    total = len(_test_cases)
    print(f'{passed}/{total} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for case_num, expected, actual, err in failed:
            print(f'  Test #{case_num}: {err}')
            print(f'    Expected: {expected}')
            print(f'    Got: {actual}')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Twitter)
