# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

from typing import *
from collections import *
from heapq import *
from bisect import *



# ==== YOUR SOLUTION HERE ====


# Test cases for encode-and-decode-strings
_encode_decode_cases = [
    ['Hello', 'World'],
    [''],
    ['neet', 'code', 'love', 'you'],
    ['we', 'say', ':', 'yes'],
    ['#', '1#2', '', 'spaces are valid'],
]

def check(codec):
    passed = 0
    failed = []
    for i, strs in enumerate(_encode_decode_cases, 1):
        encoded = decoded = None
        try:
            encoded = codec.encode(strs)
            decoded = codec.decode(encoded)
            assert decoded == strs
            passed += 1
        except AssertionError:
            failed.append((i, strs, decoded, 'wrong answer'))
        except Exception as e:
            failed.append((i, strs, decoded, type(e).__name__ + ': ' + str(e)))
    total = len(_encode_decode_cases)
    print(f'{passed}/{total} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, strs, decoded, err in failed:
            print(f'  Test #{i}: {err}')
            print(f'    Input: {strs}')
            print(f'    Decoded: {decoded}')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution())
