# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

from typing import *
from collections import *
from heapq import *
from bisect import *

class TreeNode:
    def __init__(self, x):
        self.val = x
        self.left = None
        self.right = None



# ==== YOUR SOLUTION HERE ====


# Test cases for lowest-common-ancestor-of-a-binary-search-tree
_test_cases = [
    ([6, 2, 8, 0, 4, 7, 9, None, None, 3, 5], 2, 8, 6),
    ([6, 2, 8, 0, 4, 7, 9, None, None, 3, 5], 2, 4, 2),
    ([2, 1], 2, 1, 2),
]

def _build_tree(values):
    if not values:
        return None, {}
    nodes = [None if v is None else TreeNode(v) for v in values]
    kids = nodes[::-1]
    root = kids.pop()
    for node in nodes:
        if node:
            if kids:
                node.left = kids.pop()
            if kids:
                node.right = kids.pop()
    return root, {node.val: node for node in nodes if node is not None}

def check(candidate):
    passed = 0
    failed = []
    for i, (values, p_val, q_val, expected) in enumerate(_test_cases, 1):
        try:
            root, nodes = _build_tree(values)
            result = candidate(root, nodes[p_val], nodes[q_val])
            assert result is not None and result.val == expected
            passed += 1
        except AssertionError:
            failed.append((i, expected, None if 'result' not in locals() or result is None else result.val, 'wrong answer'))
        except Exception as e:
            failed.append((i, expected, None, type(e).__name__ + ': ' + str(e)))
    print(f'{passed}/{len(_test_cases)} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, expected, got, err in failed:
            print(f'  Test #{i}: {err}; expected {expected}, got {got}')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Solution().lowestCommonAncestor)
