# Auto-generated by build_pro_deck.py — do not edit by hand.
# Paste your Solution class where indicated, then run to self-test.

from typing import *
from collections import *
from heapq import *
from bisect import *

class TreeNode:
    def __init__(self, x):
        self.val = x
        self.left = None
        self.right = None



# ==== YOUR SOLUTION HERE ====


# Test cases for serialize-and-deserialize-binary-tree
_test_cases = [[1, 2, 3, None, None, 4, 5], [], [1], [1, 2]]

def _build_tree(values):
    if not values:
        return None
    nodes = [None if v is None else TreeNode(v) for v in values]
    kids = nodes[::-1]
    root = kids.pop()
    for node in nodes:
        if node:
            if kids:
                node.left = kids.pop()
            if kids:
                node.right = kids.pop()
    return root

def _tree_to_level(root):
    out = []
    q = deque([root]) if root else deque()
    while q:
        node = q.popleft()
        if node is None:
            out.append(None)
            continue
        out.append(node.val)
        q.append(node.left)
        q.append(node.right)
    while out and out[-1] is None:
        out.pop()
    return out

def check(codec):
    passed = 0
    failed = []
    for i, values in enumerate(_test_cases, 1):
        try:
            root = _build_tree(values)
            result = codec.deserialize(codec.serialize(root))
            got = _tree_to_level(result)
            assert got == values
            passed += 1
        except AssertionError:
            failed.append((i, values, got, 'wrong answer'))
        except Exception as e:
            failed.append((i, values, None, type(e).__name__ + ': ' + str(e)))
    print(f'{passed}/{len(_test_cases)} tests passed')
    if failed:
        print(f'\n{len(failed)} test(s) failed:')
        for i, expected, got, err in failed:
            print(f'  Test #{i}: {err}; expected {expected}, got {got}')
    else:
        print('All tests passed! \u2713')
    return not failed

check(Codec())
